### ISSUE TITLE
Overlaying nav bar

### ISSUE THREAD

**Issue by lucasmarcondes** [ASWWU-Web/pages#39]
Currently, the sub-navbar is overlaying the original navbar when a drop-down menu is clicked.

![image](https://user-images.githubusercontent.com/26172645/67444636-c3423c00-f5be-11e9-9604-aeef96290b41.png)

**Comment by stephenermshar** [comment]
This will be fixed with the addition of shared-ng in Issue #45

**Comment by stephenermshar** [comment]
merged into develop, waiting for deployment

**Comment by stephenermshar** [comment]
@octagonprogramming I think you deployed this a little while back so I'm closing the issue, let me know if there was a reason it was kept open.
